# Generated by Django 3.0.5 on 2020-04-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='0000', max_length=200),
        ),
    ]
