# Generated by Django 3.0.5 on 2020-04-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200426_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
    ]
